package:
  name: <<PACKAGE_NAME>>
  version: "{{ POETRY_VERSION }}"

source:
  path: ".."

requirements:
  build:
    - python >=<<MIN_PYTHON_VERSION>>
    - pip
    - poetry

  run:
    - python >=<<MIN_PYTHON_VERSION>>
    - importlib-metadata >=4.11

build:
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed ."
  noarch: python

about:
  home: https://github.com/<<GITHUB_USERNAME>>/python-<<PACKAGE_NAME>>
  license: GPLv3
  summary: "<<PACKAGE_DESCRIPTION>>"
  description: "<<PACKAGE_DESCRIPTION>>"
  dev_url: https://github.com/<<GITHUB_USERNAME>>/python-<<PACKAGE_NAME>>
  doc_url: https://<<GITHUB_USERNAME>>.github.io/python-<<PACKAGE_NAME>>/<<PACKAGE_NAME>>